<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?php echo ATXT_MAIL_CONFIG; ?></div>

<form class="admin-form form-big" id="admin_edit_mail_config" name="admin_edit_smail_config" role="form" method="post" action="">
 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">

     <label for="mail_connection" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>">  * <?= FORM_EMAIL_CONNECTION_SORT; ?>  </label>
     <select class="selectpicker" id="mail_connection" name="mail_connection"  data-live-search="false"  data-show-tick="true">
      <option data-subtext="" value="none" data-tokens=""> <?= AMENU_PICK_ONE; ?> </option>
       <option data-subtext="" data-tokens="" value="phpmail"><?= FORM_SMTP_IS_NO;?></option>
      <option data-subtext="" data-tokens="" value="smtp"><?= FORM_SMTP_IS;?></option>
     </select>
    </div>

 </div>
</div>
 <div id="show-smtp">
 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="mail_smtp_host" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_SMTP_HOST; ?>  </label>
    <input type="text" class="form-control " id="mail_smtp_host" name="mail_smtp_host" value="<?php if(isset($site['mail_smtp_host'])){echo $site['mail_smtp_host'];} ?>"/>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="mail_smtp_port" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_SMTP_PORT; ?>  </label>
    <input type="text" class="form-control " id="mail_smtp_port" name="mail_smtp_port" value="<?php if(isset($site['mail_smtp_port'])){echo $site['mail_smtp_port'];} ?>"/>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="mail_smtp_user" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_SMTP_USER; ?>  </label>
    <input type="text" class="form-control " id="mail_smtp_user" name="mail_smtp_user" value="<?php if(isset($site['mail_smtp_user'])){echo $site['mail_smtp_user'];} ?>"/>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="mail_smtp_pass" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_SMTP_PASS; ?>  </label>
    <input type="text" class="form-control " id="mail_smtp_pass" name="mail_smtp_pass" value="<?php if(isset($site['mail_smtp_pass'])){echo $site['mail_smtp_past'];} ?>"/>
   </div>
  </div>
 </div>
</div>

 <div class="row">
  <div class="col-lg-12"><button type="submit" class="btn btn-default" id="send-addCategory-admin"><?php echo AMENU_SAVE; ?></div>
 </div>
</form>