<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?php echo ATXT_OWNER_CONFIG; ?></div>

<?php if(isset($param) && $param == 'edit'): ?>
 <?php if(isset($site)): ?>
<form class="admin-form form-big" id="admin_owner_config" name="admin_owner_config" role="form" method="post" action="/admin/configs/saveOwner">
 <input type="hidden" name="param" value="edit"/>
 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_name_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_NAME; ?>  </label>
    <input type="text" class="form-control " id="owner_name_edit" name="owner_name_edit" value="<?= $site['owner_name'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_surname_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_SURNAME; ?>  </label>
    <input type="text" class="form-control " id="owner_surname_edit" name="owner_surname_edit" value="<?= $site['owner_surname'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_firm_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_FIRM; ?>  </label>
    <input type="text" class="form-control " id="owner_firm_edit" name="owner_firm_edit" value="<?= $site['owner_firm'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_title_edit" data-toggle="tooltip" data-placement="top" title="<?= FORM_TIPS_TITLE; ?>"> <?= FORM_TITLE; ?>  </label>
    <input type="text" class="form-control " id="owner_title_edit" name="owner_title_edit" value="<?= $site['owner_title'] ?>" />
   </div>
  </div>
 </div>

 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_street_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_STREET; ?>  </label>
    <input type="text" class="form-control " id="owner_street_edit" name="owner_street_edit" value="<?= $site['owner_street'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_postcode_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_POSTCODE; ?>  </label>
    <input type="text" class="form-control " id="owner_postcode_edit" name="owner_postcode_edit" value="<?= $site['owner_postcode'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_city_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_CITY; ?>  </label>
    <input type="text" class="form-control " id="owner_city_edit" name="owner_city_edit" value="<?= $site['owner_city'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_country_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_COUNTRY; ?>  </label>
    <input type="text" class="form-control " id="owner_country_edit" name="owner_country_edit" value="<?= $site['owner_country'] ?>" />
   </div>
  </div>
 </div>

 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_nip_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_NIP; ?>  </label>
    <input type="text" class="form-control " id="owner_nip_edit" name="owner_nip_edit" value="<?= $site['owner_nip'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_regon_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_REGON; ?>  </label>
    <input type="text" class="form-control " id="owner_regon_edit" name="owner_regon_edit" value="<?= $site['owner_regon'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_phone_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_PHONE; ?>  </label>
    <input type="text" class="form-control " id="owner_phone_edit" name="owner_phone_edit" value="<?= $site['owner_phone'] ?>" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="owner_email_edit" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_EMAIL; ?>  </label>
    <input type="email" class="form-control " id="owner_email_edit" name="owner_email_edit" value="<?= $site['owner_email'] ?>" />
   </div>
  </div>
 </div>
 <div class="row">
  <div class="col-lg-12"><button type="submit" class="btn btn-default" id="send-addCategory-admin"><?php echo AMENU_SAVE; ?></div>
 </div>
</form>
 <?php endif; ?>

 <?php else: ?>

 list owner params
<?php endif; ?>