<div class="row">
 <div class="col-lg-12">
  <?php if(isset($message)){ echo $message; unset($message);} ?>
 </div>
</div>
<div class="team-boxed">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">cimesCMS Futures </h2>
            <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae.</p>
        </div>
        <div class="row people">
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/1.jpg">
                    <h3 class="name">Articles & news</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/2.jpg">
                    <h3 class="name">Forms & quizes</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/3.jpg">
                    <h3 class="name">Multiple galleries</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
        </div>
        <div class="row people">
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/1.jpg">
                    <h3 class="name">Courses & students</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/2.jpg">
                    <h3 class="name">Downloadable files</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/3.jpg">
                    <h3 class="name">Archives</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
        </div>
        <div class="row people">
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/1.jpg">
                    <h3 class="name">Multiple menus</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/2.jpg">
                    <h3 class="name">Changable themes</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 item">
                <div class="box"><img class="img-circle" src="images/css/3.jpg">
                    <h3 class="name">Multiple languages</h3>
                    <p class="title">bla</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i></a></div>
                </div>
            </div>
        </div>
    </div>
</div>