<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?php echo AMENU_EDIT_MENU_ITEM; ?></div>
<?php if(isset($data) && !empty($data)): ?>
 <form class="admin-form form-big" id="admin_add_menu_item_form" name="admin_add_menu_item_form" role="form" method="post" action="../menus/editMenuItemSave">
  <?php foreach($data as $item): ?>
   <input type="hidden" name="menuitem_id" value="<?php echo $item['menu_item_id']; ?>"/>
   <input type="hidden" name="menuitem_type_name" value="<?php echo $item['menu_type_name']; ?>"/>
  <div class="row margin-bottom">
   <div class="col-lg-3">
    <div class="form-group no-margin">
     <label for="menuitem_name" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?php echo TEXT_REQUIRED; ?>"> * <?php echo AMENU_MENUITEM_NAME; ?>  </label>
     <input type="text" id="menuitem_name" name="menuitem_name" class="form-control" value="<?php echo $item['menu_item_name']; ?>" />
    </div>
   </div>
   <div class="col-lg-3">
    <div class="input-group">
     <label class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?php echo TEXT_REQUIRED; ?>"> * <?php echo constant($item['menu_type_name']);?></label>
     <label for="menuitem_edit_type">
      <select class="selectpicker" id="menuitem_edit_type" name="menuitem_edit_type" data-live-search="true" data-live-search-placeholder="<?php echo AMENU_SEARCH; ?>" data-show-tick="true">
       <?php $menu_types = \App\Models\Admin\Menu::getMenuTypes(); ?>
       <option data-subtext="" value="none" data-tokens=""><?php echo AMENU_PICK_ONE; ?></option>
       <?php foreach($menu_types as $type): ?>
        <option data-subtext="" value="<?php echo $type['menu_type_list_id']; ?>" data-tokens=""><?php echo constant($type['menu_type_list_name']); ?></option>
       <?php endforeach; ?>
      </select>
     </label>
    </div>
   </div>
   <div class="col-lg-3">
    <div class="input-group">
     <div class="dynamic-ajax-call"></div>
    </div>
   </div>
  </div>
  <div class="row">
   <div class="col-lg-12"><button type="submit" class="btn btn-default full-width" id="edit_menu_item"><?php echo AMENU_SAVE_MENU; ?></div>
  </div>
  <?php endforeach; ?>
 </form>
<?php else: ?>
 <div class="row margin-bottom">
  <div class="col-lg-12"><a href="list"><?php echo TEXT_BACK; ?></a></div>
 </div>
<?php endif; ?>