<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= ATXT_GROUPS_EDIT; ?></div>

<?php if(isset($data)): ?>
<form class="admin-form form-big" id="admin_add_group" name="admin_add_group" role="form" method="post" action="">
 <div class="row margin-bottom">
  <div class="col-lg-4">
   <div class="form-group no-margin">
    <input type="hidden" id="group-course-id" name="group-course-id" class="form-control" value="<?= $data['courses_groups_id']; ?>"/>
    <?php $course_name = \App\Models\Admin\Course::getCourseNameById($data['courses_groups_id']); ?>
    <label for="group-curse-id" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= ATXT_GROUPS_COURSE_NAME; ?>  </label>
    <input type="text" id="group-curse-name" name="group-curse-name" class="form-control" disabled="disabled" value="<?= $course_name; ?>"/>
   </div>
  </div>
  <div class="col-lg-4">
   <div class="form-group no-margin">
    <label for="group-name" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>">  * <?= ATXT_GROUPS_NAME; ?>  </label>
    <input type="text" id="group-name" name="group-name" class="form-control" value="<?= $data['courses_groups_name']; ?>"/>
   </div>
  </div>
  <?php $folder = \Core\Filesystem::getFolderFromPath($data['courses_groups_folder']); ?>
  <div class="col-lg-4">
   <div class="form-group no-margin">
    <label for="group-folder" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?php echo TEXT_REQUIRED; ?>">  * <?= ATXT_GROUPS_FOLDER; ?>  </label>
    <input type="text" id="group-folder" name="group-folder" class="form-control" value="<?= $folder; ?>"/>
    <input type="hidden" id="group-old-folder" name="group-old-folder" class="form-control" value="<?= $folder; ?>"/>
   </div>
  </div>
 </div>

 <div class="row margin-bottom">
  <div class="col-lg-4">
   <div class="form-group no-margin">
    <label for="group-curse-login" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> * <?= ATXT_GROUPS_LOGIN; ?>  </label>
    <input type="text" id="group-curse-login" name="group-curse-login" class="form-control" value="<?= $data['courses_groups_login']; ?>"/>
   </div>
  </div>
  <div class="col-lg-4">
   <div class="form-group no-margin">
    <label for="group-curse-pass" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>">  * <?= ATXT_GROUPS_PASS; ?>  </label>
    <input type="password" id="group-curse-pass" name="group-curse-pass" class="form-control" value=""/>
   </div>
  </div>

  <div class="col-lg-4">
   <div class="form-group no-margin">
    <div class="row">
     <div class="col-sm-6">
      <div class="form-group no-margin">
       <label for="group-show-pass" class="" data-toggle="tooltip" data-placement="top" title=""> <?= ATXT_GROUPS_SHOW_PASS; ?>  </label>
       <select class="selectpicker selectpicker-small" id="group-show-pass" data-live-search="false" data-show-tick="true">
        <option data-subtext="" value="no" data-tokens="" selected="selected"> <?= TEXT_NO; ?> </option>
        <option data-subtext="" value="yes" data-tokens=""> <?= TEXT_YES; ?> </option>
       </select>
      </div>
     </div>
     <div class="col-sm-6">
      <div class="form-group no-margin">
      <button type="button" class="btn btn-default" id="pass-gen"><?= ATXT_GROUPS_GEN_PASS; ?></button>
       </div>
     </div>
    </div>
   </div>
  </div>
 </div>
 <div class="row">
  <div class="col-lg-12"><button type="submit" class="btn btn-default" id="add_class" name="add_class"><?php echo AMENU_CLASS_SAVE; ?></div>
 </div>
</form>
<?php endif; ?>
<?php if(isset($success)): ?>
 <?php echo $success; ?>
<?php endif; ?>
