<?php
/**
 * Creator: BabooJaga
 * Date: 2016-04-17
 * Time: 10:01
 */
?>
<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= ATXT_TEMPLATE_EDIT; ?></div>
<?php if(isset($templates) && !empty($templates)): ?>

<form class="form-big" id="add_template" name="add_template" role="form" method="post" action="/admin/templates/edit">
    <input type="hidden" name="template_id" value="<?= $templates['id']; ?>" />
    <div class="row no-margin">
        <div class="col-lg-4">
            <div class="form-group">
                <label for="template_name" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"><?= ATXT_TEMPLATE_NAME; ?></label>
                <input type="text" class="form-control input-sm" id="template_name" name="template_name"  value="<?= $templates['template_name']; ?>" required/>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label for="template_folder" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"><?= ATXT_TEMPLATE_FOLDER; ?></label><span class="input-error" id="vName"></span>
                <input type="text" class="form-control input-sm" id="template_folder" name="template_folder"  value="<?= $templates['template_folder']; ?>" required/>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label for="template_author" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"><?= ATXT_TEMPLATE_AUTHOR; ?></label><span class="input-error" id="vName"></span>
                <input type="text" class="form-control input-sm" id="template_author" name="template_author"  value="<?= $templates['template_author']; ?>"/>
            </div>
        </div>
    </div>
    <div class="row no-margin">
        <div class="col-lg-12">
            <div class="checkbox">
                <label for="template_admin" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= ATXT_TEMPLATE_CHECK_IF_BACKEND; ?>">
                    <input type="checkbox" value="" id="template_admin" name="template_admin" <?php if($templates['template_is_admin'] == 1): ?> checked="checked" <?php endif; ?> />
                    <?= ATXT_TEMPLATE_BACKEND; ?>?
                </label>
            </div>
        </div>
    </div>
    <div class="row no-margin">
        <div class="col-lg-12">
            <div class="checkbox">
                <label for="template_active" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= ATXT_TEMPLATE_CHECK_IF_ACTIVE; ?>">
                    <input type="checkbox" value="" id="template_active" name="template_active" <?php if($templates['template_active'] == 1): ?> checked="checked" <?php endif; ?>/>
                    <?= ATXT_TEMPLATE_ACTIVE; ?>?
                </label>
            </div>
        </div>
    </div>
    <div class="row no-margin">
        <div class="col-lg-12">
            <button type="submit" class="btn btn-default pull-right" id="save-new-template"><?= AMENU_SAVE; ?></button>
        </div>
    </div>

</form>

<?php endif; ?>
