<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= ATXT_FILES_LIST; ?></div>
<?php $clist = \App\Models\Admin\File::getFCategories(); ?>
<?php if($clist != FALSE): ?>
<div class="row no-margin">
    <div class="col-lg-6 no-padding">
        <div id="pick-file-category" class="pull-left">
            <label for="select-file-category">
                <select class="selectpicker" id="select-file-category" name="select-file-category" data-live-search="true" data-live-search-placeholder="<?= AMENU_SEARCH; ?>" data-show-tick="true">
                    <option data-subtext="" value="0" data-tokens=""><?= AMENU_SELECT_CATEGORY; ?></option>
                    <?php foreach($clist as $cat): ?>
                        <option data-subtext="<?= ATXT_FILES; ?>" value="<?= $cat['id']; ?>" data-tokens="<?= $cat['name']; ?>"><?= $cat['name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
        </div>
      </div>
<?php if(isset($files)): ?>
        <div class="col-lg-6 no-padding">
            <div id="pick-file-action" class="pull-right">
                <label for="select-file-action">
                    <select class="selectpicker" id="select-file-action" name="select-file-action" data-live-search="false" data-show-tick="true">
                        <option data-subtext="" value="0" data-tokens=""><?= AMENU_ACTION; ?></option>
                        <option data-subtext="plik/pliki" value="delete" data-tokens=""><?= TEXT_DELETE; ?></option>
                        <option data-subtext="plik" value="edit" data-tokens=""><?= TEXT_EDIT; ?></option>
                    </select>
                </label>
            </div>
        </div>
    </div>
    <table class="table table-responsive table-hover table-galleries table-files">
        <thead style="background-color: #F5F5F5;">
        <tr>
            <th width="1%" class="cell-bordered-right"><span class="check-all">#</span></th>
            <th class="cell-bordered-right"><?= ATXT_FILE_TYPE; ?></th>
            <th class="cell-bordered-right"><?= ATXT_FILE_NAME; ?></th>
            <th class="cell-bordered-right"><?= ATXT_FILE_CATEGORY; ?></th>
            <th class="cell-bordered-right"><?= ATXT_FILE_PATH; ?></th>
            <th class="cell-bordered-right"><?= ATXT_FILE_TITLE; ?></th>
            <th class="cell-bordered-right"><?= ATXT_FILE_DATE; ?></th>
            <th class="cell-bordered-right"><?= ATXT_FILE_UPLOADER; ?></th>
            <th><?= ATXT_FILE_DOWNLOADED; ?></th>
        </tr>
        </thead>
        <tbody class="gallery-table-body">
        <form id="form-files-action" name="form-files-action" action="" method="POST">
            <?php foreach($files as $file): ?>
            <?php $ico = \Core\Filesystem::matchImageToExt($file['type']); ?>
                <tr>
                    <td scope="row" class="cell-bordered-right"><input type="checkbox" class="checkbox-inputs" id="file_<?= $file['id']; ?>" name="file_<?= $file['id']; ?>" value="<?= $file['id']; ?>"/></td>
                    <td class="cell-bordered-right"><img class="img-responsive file-ico" src="/images/mime/<?= $ico; ?>.png"></td>
                    <td class="cell-bordered-right"> <?= $file['name'];?></td>
                    <td class="cell-bordered-right centered"><?= $file['category_name'];?></td>
                    <td class="cell-bordered-right"><a href="<?= $file['path'];?>" target="_blank"><?= $file['path'];?></a></td>
                    <td class="cell-bordered-right"><?= $file['title'];?></td>
                    <td class="cell-bordered-right"><?php if($file['date_edited'] != NULL): ?><?= $file['date_edited'];?> <?php else: ?> <?= $file['date_added'];?><?php endif; ?></td>
                    <td class="cell-bordered-right"><?php if($file['edited_by'] != ''): ?><?= $file['edited_by'];?> <?php else: ?><?= $file['uploaded_by'];?><?php endif; ?></td>
                    <td><?= $file['downloaded'];?></td>
                </tr>
            <?php endforeach; ?>
        </form>
        </tbody>
    </table>
<?php endif; ?>

<?php if(!isset($files)): ?>
</div>
<?php endif; ?>

<?php else: ?>

    <div class="row no-margin">
        <div class="col-lg-12">
            <div class="message-warning"><?= ATXT_NO_CATEGORY_TYPE_FILE; ?></div>
        </div>
    </div>

<?php endif; ?>

<?php if(isset($files)):?>
    <div id="confirm-delete-files">
        <input type = "hidden" id="delete-file-confirmation" value="<?= AMENU_FILE_DELETE_CONFIRM; ?>" />
        <input type = "hidden" id="btn-continue" value="<?= ABTN_CONTINUE; ?>" />
        <input type = "hidden" id="btn-cancel" value="<?= ABTN_CANCEL; ?>" />
        <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span><?= ATXT_FILE_DELETE_CONFIRM; ?>? </p>
    </div>
<?php endif; ?>