<?php
/**
 * Creator: BabooJaga
 * Date: 2016-04-17
 * Time: 10:01
 */
?>
<div class="content-page-holder">
    <div class="content-wrapper">
        <div class="message-frontend"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
        <?php if(isset($list) && !empty($list)): ?>
            <?php $iterator = 0;?>
            <div class="row no-margin">
            <?php foreach($list as $gallery): ?>
                <?php $metaname = \App\Models\Admin\Menu::getGallerySeoLink($gallery['gallery_id']); ?>
                    <div class="col-lg-4">
                        <a href="/galleries/<?= $gallery['gallery_id'];?>/<?= $metaname; ?>" class="subcategory-table-link">
                        <div class="sub-list-holder">
                            <h1 class="standart-sub-list-article-name"><?= $gallery['gallery_name'];?></h1>
                            <img class="img-responsive sub-category-desc-image-grid" src="<?= $gallery['thumbnail'];?>" />
                            <p class="p-standart-category-description"><?= $gallery['gallery_description'];?></p>
                        </div>
                        </a>
                    </div>
                    <?php $iterator++; ?>
                    <?php if($iterator >= 3): ?>
                        </div>
                        <?php $iterator = 0; ?>
                        <div class="row no-margin"> 
                    <?php endif; ?>
            <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</div>


