<?php
/**
 * Creator: BabooJaga
 * Date: 2016-04-17
 * Time: 10:01
 */
?>
<div class="content-page-holder">
    <div class="content-wrapper">
        <div class="message-frontend"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
        <?php if(isset($list) && !empty($list)): ?>
            <?php foreach($list as $gallery): ?>
                    <div class="row no-margin">
                        <div class="col-lg-12">
                            <a href="/galleries/<?= $gallery['gallery_id'];?>/items" class="subcategory-table-link">
                                <div class="sub-list-holder">
                                    <h1 class="standart-sub-list-article-name"><?= $gallery['gallery_name'];?></h1>
                                    <div class="row">
                                        <div class="col-lg-2">
                                            <img class="img-responsive sub-category-desc-image" src="<?= $gallery['thumbnail'];?>" />
                                        </div>
                                        <div class="col-lg-10">
                                            <?= $gallery['description'];?>
                                        </div>
                                    </div>
                                </div></a>
                        </div>
                    </div>
                <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
