<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= AMENU_ADD_STUDENT; ?></div>
<?php $groups = \App\Models\Admin\Course::listAllGroups(); ?>
<form class="admin-form form-big" id="admin_add_student" name="admin_add_student" role="form" method="post" action="">
 <!-- first data set -->
 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="student-group-select" data-toggle="tooltip" data-placement="top" title="<?= TOOLTIP_GROUPS_SELECT; ?>"> <?= ATXT_GROUPS_SELECT; ?>  </label>
    <select class="selectpicker" id="student-group-select" name="student-group-select"  data-live-search="true" data-live-search-placeholder="<?= AMENU_SEARCH; ?>" data-show-tick="true">
     <option data-subtext="" value="none" data-tokens=""> <?= AMENU_SELECT; ?> </option>
     <?php foreach($groups as $group): ?>
      <option data-subtext="<?= ATXT_GROUP; ?>" data-tokens="<?= $group['courses_groups_name'];?>" value="<?= $group['courses_groups_id'];?>"><?= $group['courses_groups_name'];?></option>
     <?php endforeach; ?>
    </select>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-name" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> * <?= FORM_NAME; ?>  </label>
    <input type="text" id="student-name" name="student-name" class="form-control" required/>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-surname" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> * <?= FORM_SURNAME; ?>  </label>
    <input type="text" id="student-surname" name="student-surname" class="form-control" required/>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-title" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= FORM_TIPS_TITLE; ?>"> <?= FORM_TITLE; ?>  </label>
    <input type="text" id="student-title" name="student-title" class="form-control"/>
   </div>
  </div>
 </div>
 <!-- second data set -->
 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-street" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_STREET; ?>  </label>
    <input type="text" id="student-street" name="student-street" class="form-control"/>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-postcode" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_POSTCODE; ?>  </label>
    <input type="text" id="student-postcode" name="student-postcode" class="form-control" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-city" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_CITY; ?>  </label>
    <input type="text" id="student-city" name="student-city" class="form-control" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-region" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_REGION; ?>  </label>
    <input type="text" id="student-region" name="student-region" class="form-control"/>
   </div>
  </div>
 </div>
 <!-- third data set -->
 <div class="row margin-bottom">
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-country" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_COUNTRY; ?>  </label>
    <input type="text" id="student-country" name="student-country" class="form-control"/>
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-email" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>" > * <?= FORM_EMAIL; ?>  </label>
    <input type="email" id="student-email" name="student-email" class="form-control" required />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label for="student-additional" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= FORM_ADD_NOTE; ?>  </label>
    <input type="text" id="student-additional" name="student-additional" class="form-control" />
   </div>
  </div>
  <div class="col-lg-3">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="student-newsletter-select" data-toggle="tooltip" data-placement="top" title="<?= TOOLTIP_NEWSLETTER_SELECT; ?>"> <?= MAIL_NEWSLETTER; ?>  </label>
    <select class="selectpicker" id="student-newsletter-select" name="student-newsletter-select"  data-live-search="true" data-live-search-placeholder="<?= AMENU_SEARCH; ?>" data-show-tick="true">
     <option data-subtext="" value="none" data-tokens=""> <?= AMENU_SELECT; ?> </option>
     <?php $newsletters = \App\Models\Admin\Mail::getNewsletterList(); foreach($newsletters as $newsletter): ?>
      <option data-subtext="" data-tokens="<?= $newsletter['newsletter_title'];?>" value="<?= $newsletter['newsletter_id'];?>"><?= $newsletter['newsletter_title'];?></option>
     <?php endforeach; ?>
    </select>
   </div>
  </div>
 </div>

 <!-- SUBMIT -->
 <div class="row">
  <div class="col-lg-12"><button type="submit" class="btn btn-default" id="add_student" name="add_student"><?= AMENU_SAVE; ?></div>
 </div>
</form>