<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div id="errorBlock"></div>
<div class="page-header"><?php echo AMENU_ADD_CATEGORY; ?></div>
<?php $type_list = \App\Models\Admin\Category::getType(); ?>

<form class="admin-form form-big" id="admin_add_category" name="admin_add_category" role="form" method="post" action="" enctype="multipart/form-data">
<div class="category-wrapper">
<div class="row second-row">
     <div class="col-lg-12 table-cell table-header">
        <?php echo AMENU_CATEGORY_BASIC; ?>
     </div>
</div>
    <div class="row">
        <div class="col-lg-3 table-cell">
        <div class="input-group">
            <input type="file" id="category_image_add" name="category_image_add" />
        </div>
            <div class="thumbnail-placeholder">
                <div class="thumbnail-placeholder-label"><?php echo ATXT_SELECT_IMAGE; ?></div>
            </div>
        </div>
        <div class="col-lg-4 table-cell">
            <div class="row">
                <div class="col-lg-12 table-cell">
                    <div class="input-group">
                        <label for="set_cat_type" id="label_set_cat_type">
                            <select class="selectpicker" id="set_cat_type" name="set_cat_type" data-live-search="true" data-live-search-placeholder="<?= AMENU_SEARCH; ?>" data-show-tick="true">
                                <option data-subtext="" value="none" data-tokens=""><?= AMENU_SELECT_CATEGORY_TYPE; ?></option>
                                <?php foreach($type_list as $type): ?>
                                    <?php $t = \App\Models\Admin\Category::getCategoryTypeName($type['type_id']); ?>
                                    <?php $count = \App\Models\Admin\Category::checkAvaiability($type['type_id']); ?>
                                    <option data-subtext="" value="<?php echo $type['type_id']; ?>" data-tokens="<?php echo $t;?>"><?php echo $t. ' ('.$count.')';?></option>
                                <?php endforeach; ?>
                        </label>
                        </select>
                        </label>
                    </div>
                </div>
            </div>
        <div class="row">
            <div class="col-lg-12 table-cell">
                <div class="input-group">
                    <label for="set_cat_parent" id="label_set_cat_parent">
                        <select class="selectpicker" id="set_cat_parent" name="set_cat_parent"  data-live-search="true" data-live-search-placeholder="<?php echo AMENU_SEARCH_CATEGORY; ?>" data-show-tick="true">
                            <option data-subtext="" value="none" data-tokens=""><?php echo AMENU_SELECT_CATEGORY_PARENT; ?></option>
                            <option data-subtext="" value="main" data-tokens=""><?php echo AMENU_CATEGORY_MAIN; ?></option>
                            <?php if(isset($_SESSION['cat_type_id'])): ?>
                                <?php $ctype_id = $_SESSION['cat_type_id']; ?>
                                <?php \Core\Session::delete('cat_type_id'); ?>
                            <?php $category_list = \App\Models\Admin\Category::categoryGetList(0, $ctype_id); ?>
                            <?php \App\Models\Admin\Category::recursivePrint($category_list); ?>
                            <?php endif; ?>
                    </select>
                    </label>
                    <input type="hidden" id="ctype-for-jquerry" value="<?php if(isset($ctype_id)){echo $ctype_id;}else{echo '0';}?>"/>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 table-cell">
                    <div class="form-group no-margin">
                        <input type="text" class="form-control " id="add_catname" name="add_catname"  placeholder="<?php echo AMENU_ADD_CATEGORY_NAME; ?>"/>
                    </div>
                </div>
            </div>
        </div>
        </div><!-- end second col -->
        <div class="col-lg-5 table-cell">
            <div class="form-group">
                <textarea class="form-control textarea-table tinymce-container" placeholder="<?php echo AMENU_CATEGORY_DESCRIPTION; ?>" rows="6" id="add_catdescription" name="add_catdescription"></textarea>
            </div>
        </div>
    </div><!-- end main row -->
    <div class="row second-row">
        <div class="col-lg-12 table-cell table-header">
            <?php echo AMENU_CATEGORY_SEO; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 table-cell">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <input type="text" class="form-control textarea-table" id="add_metacatname" name="add_metacatname"  placeholder="<?php echo AMENU_CATEGORY_ADD_METANAME; ?>"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <input type="text" class="form-control textarea-table" id="add_metacatkeys" name="add_metacatkeys"  placeholder="<?php echo AMENU_CATEGORY_ADD_METAKEYS; ?>"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 table-cell">
            <div class="form-group">
                <textarea class="form-control textarea-table" placeholder="<?php echo AMENU_CATEGORY_METADESCRIPTION; ?>" rows="3" id="add_metacatdescription" name="add_metacatdescription"></textarea>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12"><button type="submit" class="btn btn-default" id="send-addCategory-admin"><?php echo AMENU_CATEGORY_SAVE; ?></div>
    </div>
</div>
</form>