<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN">
<html lang="pl" xml:lang="pl" xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>cimesCms pomoc </title>
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta content="text/html; charset=utf-8" http-equiv="content-type">
<meta content="" name="description">
<meta content="" name="keywords">
<link media="screen" type="text/css" href="files/css/bootstrap.min.css" rel="StyleSheet">
<link media="screen" type="text/css" href="files/css/help.css" rel="StyleSheet">

<script type="text/javascript" src="files/js/jquery-1.12.0.min.js"></script>
 <script type="text/javascript" src="files/js/bootstrap.min.js"></script>
<script type="text/javascript" src="files/js/help.js"></script>
</head>
<body>
<div class="main-container">
