<ul class="nav nav-pills help-menu-pills nav-stacked">

 <li class="nav-pills-header">Zaplecze (backend)</li>
 <ul class="nav nav-pills help-menu-pills nav-stacked">
  <li class="nav-pills-header-l2">Temat 1</li>
  <li><a href="#">Menu 1</a></li>
  <li><a href="#">Menu 2</a></li>
  <li><a href="#">Menu 3</a></li>
 </ul>

 <li class="nav-pills-header">Strona (frontend)</li>
 <ul class="nav nav-pills help-menu-pills nav-stacked">
  <li class="nav-pills-header-l2">Temat 2</li>
  <li><a href="#">Menu 1</a></li>
  <li><a href="#">Menu 2</a></li>
  <li><a href="#">Menu 3</a></li>
 </ul>

</ul>