<?php
/**
 * Created by Zbigglord
 * Company: HELLUX
 * Date: 2017-11-30
 * Time: 13:40
 */
?>
<?php if(isset($slider_id)): ?>
<?php $slider = \App\Models\Admin\Medium::getSliderHeader($slider_id); ?>
<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= AMENU_SLIDER_EDIT; ?></div>
<form class="admin-form form-big" id="add_slider_form" name="add_slider_form" role="form" method="post" action="/admin/media/editslider" enctype="multipart/form-data">
    <input type="hidden" id="slider_id" name="slider_id" class="form-control" value="<?= $slider['slider_id'];?>"/>
    <div class="row no-margin">
        <div class="col-lg-7 no-padding-left">
            <div class="form-group no-margin">
                <label for="slider_name">* <?=AMENU_SLIDER_NAME;?></label>
                <input type="text" id="slider_name" name="slider_name" class="form-control" value="<?= $slider['slider_name'];?>"/>
            </div>
        </div>
        <div class="col-lg-3 no-padding">
            <div class="form-group no-margin">
                <p class="no-margin"> <label for="slider_active" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?=TEXT_REQUIRED; ?>"> * <?=AMENU_SLIDER_ACTIVE; ?></label></p>
                <select class="selectpicker" id="slider_active" name="slider_active" data-live-search="false" data-show-tick="true">
                    <option data-subtext="" value="1" data-tokens="" <?php if($slider['slider_active'] == 1): ?> selected <?php endif; ?>> <?=TEXT_YES; ?> </option>
                    <option data-subtext="" value="0" data-tokens="" <?php if($slider['slider_active'] != 1): ?> selected <?php endif; ?>> <?=TEXT_NO; ?> </option>
                </select>
            </div>
        </div>
        <div class="col-lg-2 no-padding">
            <div class="form-group no-margin">
                <p class="no-margin"><label for="">&nbsp;</label></p>
                <button type="submit" class="btn btn-default full-width" id="slider_save"><?=AMENU_SAVE; ?></button>
            </div>
        </div>
    </div>
</form>
<?php endif; ?>