<div class="row">
 <div class="col-lg-12">
  <?php if(isset($message)){ echo $message; unset($message);} ?>
 </div>
</div>
<div class="fe-form-holder">
 <div class="fe-form-header mb-20">Logowanie</div>
 <form role="form" name="fe-form-login" class="fe-form form-small" method="post" action="<?=ROOT_ADDRESS; ?>/users/index">
  <div class="form-group">
   <input id="fe-login-email" class="form-control hellux-input-text hellux-login-input" type="text" name="fe-login-login" placeholder="<?= FTXT_LOGIN; ?>"/>
  </div>
  <div class="form-group">
   <input id="fe-login-pass" class="form-control hellux-input-text hellux-login-input" type="password" name="fe-login-pass" placeholder="<?= FTXT_PASS; ?>"/>
  </div>
  <button id="fe_login_send" class="fe-login-btn" type="submit"><?= FTXT_LOGIN; ?></button>
 </form>
</div>