<div class="content-page-holder">
 <div class="content-wrapper">
  <div class="message-frontend"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
  <div class="front-page-header margin-bottom-big">Kursy i szkolenia</div>
  <?php if(isset($clist)): ?>
   <div class="row margin-bottom-big">
 <?php $i=1; foreach($clist as $course): ?>
   <div class="col-lg-4">
    <div class="one-course-holder">
      <div class="row">
        <div class="col-sm-3">
         <img class="img-responsive thumbnail course-list-thumbnail" src="<?php echo $course['courses_display_data_image']; ?>" />
        </div>
       <div class="col-sm-9 no-padding">
       <p class="course-list-title"> <?php echo $course['courses_display_data_title']; ?></p>
       </div>
       </div>
     <div class="row">
      <div class="col-sm-12"><?php echo html_entity_decode(substr($course['courses_display_data_description'],0,250)); ?> ... </div>
     </div>
     <div class="row">
      <div class="col-sm-12"><div class="course-see-all"><a href="/courses/<?php echo $course['courses_display_data_id']; ?>/course">zobacz szczegóły szkolenia</a></div></div>
     </div>
     <div class="row">
      <div class="col-sm-12"><div class="course-see-something-else"><a href="/courses/<?php echo $course['courses_display_data_id']; ?>/course">zobacz coś innego</a></div></div>
     </div>
     </div>
    </div>
  <?php $i++;?>
  <?php
   if($i ==4){
    echo '</div>';
    echo '<div class="row">';
    $i=1;
   }
  ?>
 <?php endforeach; ?>
  <?php else: ?>
  <?php endif; ?>
 </div>
</div>