<?php
/**
 * Created by Zbigglord
 * Company: HELLUX
 * Date: 2018-01-10
 * Time: 11:07
 */
?>
<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= MED_ADD_IMAGES; ?></div>

<div class="row no-margin"><!-- START MAIN ROW -->
    <div class="col-lg-12 no-padding"> <!-- START MAIN COL -->

        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="panel-title"><?= MED_ADD_GALLERY_IMAGES; ?>: <strong><?=$gallery[0]['gallery_name']; ?></strong></h1>
                    </div>
                </div>
            </div>
            <form class="form-big" id="add_media_form" name="add_media_form" role="form" method="post" action="/admin/media/addgalleryimage" enctype="multipart/form-data">
                <input type="hidden" id="gallery-id" name="gallery-id" value="<?=$gallery[0]['gallery_id']; ?>" />
                <div class="panel-body" id="panel-body-add-media-salon">
                    <div class="row no-margin">
                        <div class="col-lg-12">

                            <input type="file" id="gallery_media_add" name="gallery_media_add[]" accept="image/*" multiple="multiple"/>

                            <div class="input-placeholder">
                                <div class="input-placeholder-label"><?= FBTN_ADD_MEDIA_FILES; ?></div>
                            </div>
                        </div>
                    </div><!-- END ROW -->
                    <ul class="thums-list" style="padding-bottom: 5px;"><!-- START 5 ROW -->


                    </ul>
                </div><!-- END BODY -->
                <div class="panel-footer clearfix">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-default" id="add_pictures_gallery" disabled="disabled"><?= AMENU_SAVE; ?></button> <button type="button" class="btn btn-default" id="btn_cancel" onclick="cancel('/admin/media/galleryimages?gallery_id=<?=$gallery[0]['gallery_id']; ?>')"><?= BTN_CANCEL; ?></button>
                    </div>
                </div>
            </form>
        </div><!-- END PANEL -->
    </div> <!-- END PAGE CONTENT -->
</div> <!-- END MAIN COL -->
