<?php
/**
 * Created by Zbigglord
 * Company: HELLUX
 * Date: 2018-01-12
 * Time: 13:51
 */
?>
<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= ATXT_FORMS_NEW; ?></div>

<div class="row no-margin"><!-- START MAIN ROW -->
    <div class="col-lg-12 no-padding"> <!-- START MAIN COL -->
     <form id="create-new-formular-form" name="create-new-formular-form" method="POST" action="/admin/forms/addNewForm">
         <div class="row">
             <div class="col-lg-4">
                 <div class="form-group">
                 <label for="new-form-title" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> <?= ATXT_FORMS_NEW_TITLE; ?>  *  </label>
                 <input type="text" class="form-control" id="new-form-title" name="new-form-title" value="" required />
                 </div>
             </div>
             <div class="col-lg-4">
                 <div class="form-group">
                 <label for="new-form-name" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= ATXT_FORMS_NEW_NAME; ?>  </label>
                 <input type="text" class="form-control" id="new-form-name" name="new-form-name" value=""/>
                 </div>
             </div>
             <div class="col-lg-4">
                 <div class="form-group">
                 <label for="new-form-id" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> <?= ATXT_FORMS_NEW_ID; ?>  *  </label>
                 <input type="text" class="form-control" id="new-form-id" name="new-form-id" value="<?php if(isset($new_form_char_id)): ?><?= $new_form_char_id; ?><?php endif; ?>" readonly required/>
                 </div>
             </div>
         </div>
         <div class="row">
             <div class="col-lg-4">
                 <div class="form-group">
                 <label for="new-form-class" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= ATXT_FORMS_NEW_CLASS; ?></label>
                 <input type="text" class="form-control" id="new-form-class" name="new-form-class" value="" />
                 </div>
             </div>
             <div class="col-lg-4">
                 <div class="form-group">
                     <label for="new-form-method" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> <?= ATXT_FORMS_NEW_METHOD; ?>  * </label>
                         <select class="standart-select" id="new-form-method" name="new-form-method" data-live-search="false" data-show-tick="true">
                             <option data-subtext="" value="1">POST</option>
                             <option data-subtext="" value="2">GET</option>
                     </select>
                 </div>
             </div>
             <div class="col-lg-4">
                 <div class="form-group">
                 <label for="new-form-action" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title=""> <?= ATXT_FORMS_NEW_ACTION; ?>  </label>
                 <input type="text" class="form-control" id="new-form-action" name="new-form-action" value="" />
                 </div>
             </div>
         </div>
         <div class="row">
             <div class="col-lg-4">
                 <div class="form-group">
                     <label for="new-form-text-before" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> <?= FORM_TXT_BEFORE; ?>  * </label>
                     <select class="selectpicker" id="new-form-text-before" name="new-form-text-before" data-live-search="true" data-live-search-placeholder="<?php echo AMENU_SEARCH; ?>" data-show-tick="true">
                         <?php $posts = \App\Models\Admin\Post::listAllArticles();?>
                         <option data-subtext="" value="0" data-tokens=""><?php echo AMENU_PICK_ONE; ?></option>
                         <?php foreach($posts as $post): ?>
                             <option data-subtext="<?= $post['post_author']?>" value="<?= $post['post_id']?>" data-tokens="<?= $post['post_title']?>"><?= $post['post_title']?></option>
                         <?php endforeach; ?>
                     </select>
                 </div>
             </div>
             <div class="col-lg-4">
                 <div class="form-group">
                     <label for="new-form-text-after" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> <?= FORM_TXT_AFTER; ?>  * </label>
                     <select class="selectpicker" id="new-form-text-after" name="new-form-text-after" data-live-search="true" data-live-search-placeholder="<?php echo AMENU_SEARCH; ?>" data-show-tick="true">
                         <?php $posts = \App\Models\Admin\Post::listAllArticles();?>
                         <option data-subtext="" value="0" data-tokens=""><?php echo AMENU_PICK_ONE; ?></option>
                         <?php foreach($posts as $post): ?>
                             <option data-subtext="<?= $post['post_author']?>" value="<?= $post['post_id']?>" data-tokens="<?= $post['post_title']?>"><?= $post['post_title']?></option>
                         <?php endforeach; ?>
                     </select>
                 </div>
             </div>
             <div class="col-lg-4">
                 <div class="form-group">
                     <label for="new-form-category" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>"> <?= FORM_CATEGORY; ?>  * </label>
                     <select class="selectpicker" id="new-form-category" name="new-form-category" data-live-search="true" aria-required="true" data-live-search-placeholder="<?php echo AMENU_SEARCH; ?>" data-show-tick="true">
                         <?php $categories = \App\Models\Admin\Category::categoryGetList(0,3);?>
                         <option data-subtext="" value="0" data-tokens=""><?php echo AMENU_PICK_ONE; ?></option>
                         <?php foreach($categories as $category): ?>
                             <option data-subtext="" value="<?= $category['id']?>" data-tokens="<?= $category['name']?>"><?= $category['name']?></option>
                         <?php endforeach; ?>
                     </select>
                 </div>
             </div>
         </div>
         <div class="row">
             <div class="col-lg-12">
                 <button type="submit" class="btn btn-default pull-right" id="new-form-add-button"><?= ATXT_FORMS_CREATE ?></button>
             </div>
         </div>
     </form>
    </div> <!-- END PAGE CONTENT -->
</div> <!-- END MAIN COL -->
