<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//PL">
<html lang="pl" xml:lang="pl" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?=$page_title?></title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="text/html; charset=utf-8" http-equiv="content-type">
    <meta name="description" content="<?= $meta_desc; ?>">
    <meta name="keywords" content="<?= $meta_keys; ?>">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&subset=latin-ext" rel="stylesheet">
    <link media="screen" type="text/css" href="/css/bootstrap.min.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/css/bootstrap-select.min.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/css/style.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/css/jquery-ui.min.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/css/jquery.fancybox.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/css/ionicons.min.css" rel="StyleSheet">

    <script type="text/javascript" src="/js/jquery-1.12.0.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap-select.min.js"></script>
    <script type="text/javascript" src="/js/jquery.fancybox.js"></script>
    <script type="text/javascript" src="/js/jquery.PrintArea.js"></script>
    <script type="text/javascript" src="/js/cimesCms.js"></script>
    <script type="text/javascript" src="/vendor/tinymce/tinymce.min.js"></script>
</head>
<body>