<?php
/**
 * Creator: BabooJaga
 * Date: 2016-04-17
 * Time: 10:01
 */
?>
<div class="content-page-holder">
    <div class="content-wrapper">
        <div class="message-frontend"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
        <?php if(isset($list) && !empty($list)): ?>
            <?php $iterator = 0;?>
            <div class="row no-margin">
            <?php foreach($list as $key => $value): ?>
                <?php if($key === 'parent'): ?>

                        <div class="col-lg-12 no-padding">
                            <div class="parent-list-holder">
                                <h1 class="standart-list-article-name"><?= $value['name'];?></h1>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <img class="img-responsive main-category-desc-image" src="<?= $value['image'];?>" />
                                    </div>
                                    <div class="col-lg-10">
                                        <?= $value['description'];?>
                                    </div>
                                </div>
                            </div>
                        </div>
                <?php else: ?>
                    <?php $seolink = \App\Models\Admin\Menu::getCategorySeoLink($value['id']); ?>
                        <div class="col-lg-4">
                                <div class="sub-list-holder">
                                    <h1 class="standart-sub-list-article-name"><?= $value['name'];?></h1>
                                            <img class="img-responsive sub-category-desc-image-grid" src="<?= $value['image'];?>" />
                                            <p class="p-standart-category-description"><?= substr($value['description'],46,250);?></p>
                                    <div class="see-more-button-div">
                                         <a href="/singlecategory/<?= $value['id'];?>/<?= $seolink; ?>" class="subcategory-table-link"><button class="btn btn-success">Więcej</button></a>
                                    </div>
                        </div>
                     </div>
                    <?php $iterator++; ?>
                    <?php if($iterator >= 3): ?>
                        </div>
                        <?php $iterator = 0; ?>
                        <div class="row no-margin">
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</div>