<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= ARC_RECIPIENT_EDIT; ?></div>
<?php if(isset($rlist)):?>
 <?php foreach($rlist as $recipient): ?>
<form class="admin-form form-big" id="admin_edit_recipient" name="admin_edit_recipient" role="form" method="post" action="/admin/mails/editRecipient">
 <input type="hidden" id="recipient-id" name="recipient-id" value="<?= $recipient['nrec_id']; ?>" />
 <input type="hidden" id="recipient-newsletter-id" name="recipient-newsletter-id" value="<?= $recipient['nrec_nesletter_id']; ?>" />
    <div class="row margin-bottom">
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-title" data-toggle="tooltip" data-placement="top" title="<?= FORM_TIPS_TITLE; ?>"> <?= FORM_TITLE; ?> </label>
       <input type="text" class="form-control " id="recipient-title" name="recipient-title" value="<?= $recipient['nrec_title']; ?>" />
      </div>
     </div>
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-name" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>">  * <?= FORM_NAME; ?> </label>
       <input type="text" class="form-control " id="recipient-name" name="recipient-name" value="<?= $recipient['nrec_name']; ?>" required />
      </div>
     </div>
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-surname" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>">  * <?= FORM_SURNAME; ?> </label>
       <input type="text" class="form-control " id="recipient-surname" name="recipient-surname" value="<?= $recipient['nrec_surname']; ?>" required />
      </div>
     </div>
    </div>
    <div class="row margin-bottom">
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-street" data-toggle="tooltip" data-placement="top"> <?= FORM_STREET; ?> </label>
       <input type="text" class="form-control " id="recipient-street" name="recipient-street" value="<?= $recipient['nrec_street']; ?>" />
      </div>
     </div>
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-postcode" data-toggle="tooltip" data-placement="top"> <?= FORM_POSTCODE; ?> </label>
       <input type="text" class="form-control " id="recipient-postcode" name="recipient-postcode" value="<?= $recipient['nrec_postcode']; ?>" />
      </div>
     </div>
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-city" data-toggle="tooltip" data-placement="top"> <?= FORM_CITY; ?> </label>
       <input type="text" class="form-control " id="recipient-city" name="recipient-city" value="<?= $recipient['nrec_city']; ?>" />
      </div>
     </div>
    </div>
    <div class="row margin-bottom">
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-city" data-toggle="tooltip" data-placement="top"> <?= FORM_REGION; ?> </label>
       <input type="text" class="form-control " id="recipient-city" name="recipient-region" value="<?= $recipient['nrec_region']; ?>" />
      </div>
     </div>
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-country" data-toggle="tooltip" data-placement="top"> <?= FORM_COUNTRY; ?> </label>
       <input type="text" class="form-control " id="recipient-country" name="recipient-country" value="<?= $recipient['nrec_country']; ?>" />
      </div>
     </div>
     <div class="col-lg-4">
      <div class="form-group no-margin">
       <label class="tooltip-labels" for="recipient-email" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>">  * <?= FORM_EMAIL; ?> </label>
       <input type="email" class="form-control " id="recipient-email" name="recipient-email" value="<?= $recipient['nrec_email']; ?>" required />
      </div>
     </div>
    </div>
 <div class="row">
  <div class="col-lg-12">
   <div id="recipient-button-no-show">
    <button type="submit" class="btn btn-default" id="admin-edit-recipient-button"><?php echo AMENU_SAVE; ?>
   </div>
  </div>
 </div>
</form>
  <?php endforeach; ?>
<?php else: ?>
 dupa
<?php endif; ?>
