<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= MAIL_NEWSLETTER_EDIT; ?></div>
<script type="text/javascript">
 tinymce.init({
  selector: '#newsletter_content',  // change this value according to your HTML
  auto_focus: '#newsletter_content',
  language : 'pl',
  relative_urls : false,
  remove_script_host : true,
  document_base_url : 'www.lbrpartner.pl',
  plugins: [
   'advlist autolink lists link image charmap print preview hr anchor pagebreak',
   'searchreplace wordcount visualblocks visualchars code fullscreen',
   'insertdatetime media nonbreaking save table contextmenu directionality',
   'template paste textcolor colorpicker textpattern imagetools'
  ],
  toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  toolbar2: 'print | forecolor backcolor | code',
  image_advtab: true
 });
</script>
<?php if(isset($newsletter)): ?>
<form class="admin-form form-big" id="admin_edit_newsletter" name="admin_edit_newsletter" role="form" method="post" action="">
 <input type="hidden" name="newsletter_id" value="<?= $newsletter['newsletter_id']; ?>"/>
 <div class="row margin-bottom">
  <div class="col-lg-6">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="newsletter_name" data-toggle="tooltip" data-placement="top" title="<?php echo TEXT_REQUIRED; ?>">  * <?= MAIL_NEWSLETTER_NAME; ?>  </label>
    <input type="text" class="form-control " id="newsletter_name" name="newsletter_name"  value="<?= $newsletter['newsletter_title']; ?>"/>
   </div>
  </div>
  <div class="col-lg-6">
   <div class="form-group no-margin" style="padding-top: 25px;">
    <label for="newsletter_active" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= TEXT_REQUIRED; ?>">  * <?= MAIL_NEWSLETTER_ACTIVE; ?>  </label>
    <select class="selectpicker" id="newsletter_active" name="newsletter_active"  data-live-search="false"  data-show-tick="true">
     <option data-subtext="" data-tokens="" value="yes" <?php if($newsletter['newsletter_active'] == 1): ?> selected <?php endif; ?>><?= TEXT_YES;?></option>
     <option data-subtext="" data-tokens="" value="no" <?php if($newsletter['newsletter_active'] == 0): ?> selected <?php endif; ?>><?= TEXT_NO;?></option>
    </select>
   </div>
  </div>
 </div>
 <div class="row margin-bottom">
  <div class="col-lg-12">
   <div class="form-group no-margin">
    <label class="tooltip-labels" for="newsletter_content" data-toggle="tooltip" data-placement="top" title="<?php echo TEXT_REQUIRED; ?>">  * <?= MAIL_NEWSLETTER_CONTENT; ?>  </label>
    <textarea class="form-control tinymce-container" id="newsletter_content" name="newsletter_content" rows="20"><?= $newsletter['newsletter_content']; ?></textarea>
   </div>
  </div>
 </div>
 <div class="row">
  <div class="col-lg-12"><button type="submit" class="btn btn-default" id="edit_newsletter"><?php echo AMENU_SAVE; ?></div>
 </div>
</form>
<?php endif; ?>