<div class="content-page-holder">
    <div class="content-wrapper">
        <div class="message-frontend"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
        <?php if(isset($plix) && !empty($plix)): ?>
            <?php foreach($plix as $plik): ?>
            <div class="row no-margin">
                <div class="col-lg-12">
                    <div class="single-file-holder">
                    <div class="file-header">
                        <div class='row no-margin'>
                            <div class="col-lg-1 no-padding-right">
                                <?php $ico = \Core\Filesystem::matchImageToExt($plik['type']); ?>
                                <img class="img-responsive file-ico" src="/images/mime/<?= $ico; ?>.png" />
                            </div>
                            <div class="col-lg-11">
                                <h1 class="standart-sub-list-file-name"><?= $plik['title'];?></h1>
                                <h2 class="standart-sub-list-file-category"><?= $plik['category_name'];?></h2>
                            </div>
                        </div>
                    </div>
                    <div class="file-body">
                        <div class="row no-margin">
                            <div class="col-lg-9 no-padding-left">
                                <div class="file-desc-holder">
                                    <p class="p-standart-category-description"><?= $plik['description'];?></p>
                                </div>
                            </div>
                            <div class="col-lg-3 no-padding-right">
                                <div class="file-attribs-holder">
                                    <p class='file-attribs-row'>
                                        <span class="file-attribs-header"><?= strtolower(FTXT_FILE_ADDED)?>: </span>
                                        <span class="file-attribs-value"><?php if($plik['date_edited'] != NULL): ?><?= $plik['date_edited'];?><?php else: ?> <?= $plik['date_added'];?> <?php endif; ?></span>
                                    </p>
                                    <p class='file-attribs-row'>
                                        <span class="file-attribs-header"><?= strtolower(FTXT_FILE_TYPE)?>: </span>
                                        <span class="file-attribs-value"><?= $plik['type'];?></span>
                                    </p>
                                    <p class='file-attribs-row'>
                                        <span class="file-attribs-header"><?= strtolower(FTXT_FILE_DOWNLOADED)?>: </span>
                                        <span class="file-attribs-value"><?= $plik['downloaded'];?></span>
                                    </p>
                                </div>
                            </div>
                        </div>

                    </div>
                        <div class="file-footer">
                            <div class="see-more-button-div">
                                <span><a href="<?= $plik['path'];?>" class="subcategory-table-link" target="_blank"><button class="btn btn-success" onclick="regDownload(<?= $plik['id'];?>)">Pobierz</button></a></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>