<div class="content-page-holder">
    <div class="content-wrapper">
        <div class="message-frontend"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
        <?php if(isset($list) && !empty($list)): ?>
            <div class="row no-margin">
                <?php foreach($list as $key => $value): ?>
                    <?php if($key === 'parent'): ?>

                        <div class="col-lg-12 no-padding">
                            <div class="parent-list-holder">
                                <h1 class="standart-list-article-name"><?= $value['name'];?></h1>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <img class="img-responsive main-category-desc-image" src="<?= $value['image'];?>" />
                                    </div>
                                    <div class="col-lg-10">
                                        <?= $value['description'];?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="col-lg-4">
                            <div class="sub-list-holder">
                                <h1 class="standart-sub-list-article-name"><?= $value['title'];?></h1>
                                <?php $ico = \Core\Filesystem::matchImageToExt($value['type']); ?>
                                <img class="img-responsive sub-category-desc-image-grid" src="/images/mime/<?= $ico; ?>.png" />
                                <p class="p-standart-category-description"><?= $value['description'];?></p>
                                <div class="see-more-button-div">
                                    <span><a href="<?= $value['path'];?>" class="subcategory-table-link" target="_blank"><button class="btn btn-success" onclick="regDownload(<?= $value['id'];?>)">Pobierz</button></a></span>
                                    <span><a href="/files/<?= $value['id'];?>/<?php if($value['metaname'] != ''): ?><?= $value['metaname']; ?><?php else: ?>file<?php endif; ?>" class="subcategory-table-link"><button class="btn btn-success">Szczegóły</button></a></span>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</div>
