<div class="row">
 <div class="col-lg-12">
  <?php if(isset($message)){ echo $message; unset($message);} ?>
 </div>
</div>
<div class="row">
 <div class="col-lg-12">
  <div class="page-header">USUWANIE DANYCH KONT EMAIL<span class="delete-buttons"><a href="/emails/list"><button class="btn btn-danger">LISTA</button></a></span></div>
 </div>
</div>
<?php if(isset($emails)): ?>
<form class="admin-form form-big" id="admin_delete_email" method="post" role="form" action="http://<?php echo $_SERVER['SERVER_NAME']?>/emails/delete">
 <?php $iter = 2; ?>
 <div class="customer-form-group">
  <div class="row header-row no-margin form-group-header">
   <div class="col-lg-1 center-aligned">Zaznacz</div>
   <div class="col-lg-3 center-aligned">Adres</div>
   <div class="col-lg-4 center-aligned">Użytkownik</div>
   <div class="col-lg-4 center-aligned">Hosting</div>
  </div>
  <?php foreach($emails as $email): ?>
   <div class="row no-margin <?php if($iter % 2 == 0): ?> second-row <?php endif; ?> table-row">
    <div class="col-lg-1 center-aligned table-cell-bordered-right"><input type="checkbox" id="<?php echo $email['hostings_email_id']; ?>" class="checkbox" name="<?php echo $email['hostings_email_id']; ?>" /></div>
    <div class="col-lg-3 center-aligned table-cell-bordered-right"><?php echo $email['hostings_email_address']; ?></div>
    <div class="col-lg-4 center-aligned table-cell-bordered-right"><?php echo $email['hostings_email_login']; ?></div>
    <?php $hostings = \App\Models\Hosting::getHostingsListById('ASC'); ?>
    <?php foreach($hostings as $hosting): ?>
     <?php if($hosting['hosting_id'] == $email['hostings_email_hosting_id']): ?>
      <div class="col-lg-4 center-aligned"><?php echo $hosting['hosting_name']; ?></div>
     <?php endif; ?>
    <?php endforeach; ?>
   </div>
   <?php $iter++; ?>
  <?php endforeach; ?>
 </div>
 <div class="row">
  <div class="col-lg-12"><button type="submit" class="btn btn-default btn-send" id="send-deleteEmail">Usuń zaznaczone</div>
 </div>
 <?php endif;?>
</form>
