<div class="row">
 <div class="col-lg-12">
  <?php if(isset($message)){ echo $message; unset($message);} ?>
 </div>
</div>
<div class="row">
 <div class="col-lg-12">
  <div class="page-header">NOWE KONTO EMAIL<span class="delete-buttons"><a href="/emails/list"><button class="btn btn-danger">LISTA</button></a></span></div>
 </div>
</div>
<form class="admin-form form-big" id="admin_add_email" method="post" role="form" action="http://<?php echo $_SERVER['SERVER_NAME']?>/emails/new">
 <div class="customer-form-group">
  <div class="form-group-header">Konto email</div>
  <div class="row no-margin table-row">
   <div class="col-lg-3">
    <div class="form-group">
     <label for="add_email_address" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="np.: email@mail.pl">* Adres email</label><span class="input-error f-right" id="vEAddress"></span>
     <input type="text" class="form-control" id="add_email_address" name="add_email_address" required/>
    </div>
   </div>
   <div class="col-lg-3">
    <div class="form-group">
     <label for="add_email_login" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="login email">* Login do konta</label><span class="input-error f-right" id="vElogin"></span>
     <input type="text" class="form-control" id="add_email_login" name="add_email_login" required/>
    </div>
   </div>
   <div class="col-lg-3">
    <div class="form-group">
     <label for="add_email_pass" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="hasło email">* Hasło do konta</label><span class="input-error f-right" id="vEPass"></span>
     <input type="text" class="form-control" id="add_email_pass" name="add_email_pass" required/>
    </div>
   </div>
   <div class="col-lg-3">
    <div class="form-group">
     <label for="pick-page-hosting" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="hostingu można szukać po: miejscu zarejestrowania, nazwie lub nazwie klienta">* Należy do hostingu</label><span class="input-error f-right" id="vHosting"></span>
     <select class="selectpicker" id="pick-page-hosting" name="pick-page-hosting" data-live-search="true" data-live-search-placeholder="<?php echo AMENU_SEARCH; ?>" data-show-tick="true">
      <option data-subtext="" value="none" data-tokens=""> <?php echo AMENU_PICK_ONE; ?> </option>
      <?php if(isset($hostings)): ?>
       <?php foreach($hostings as $hosting): ?>
        <?php $customer = \App\Models\Customer::getCustomerBy('id',$hosting['hosting_customer_id']); ?>
        <option data-subtext="<?php foreach($customer as $c){echo $c['cust_name'];} ?>" value="<?php echo $hosting['hosting_id']; ?>" data-tokens="<?php echo $hosting['hosting_register_place']; ?> <?php echo $hosting['hosting_name']; ?> <?php foreach($customer as $c){echo $c['cust_name'];} ?>"> <?php echo $hosting['hosting_name']; ?> </option>
       <?php endforeach; ?>
      <?php endif; ?>
     </select>
    </div>
   </div>
  </div>
 </div><!-- end one box -->
 <div class="row">
  <div class="col-lg-12"><button type="submit" class="btn btn-default btn-send" id="send-addEmail"><?php echo AMENU_ADD; ?></div>
 </div>
</form>