<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN">
<html lang="pl" xml:lang="pl" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?=$page_title?></title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="text/html; charset=utf-8" http-equiv="content-type">
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link media="screen" type="text/css" href="/adminfiles/css/bootstrap.min.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/adminfiles/css/bootstrap-select.min.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/adminfiles/css/style.css" rel="StyleSheet">
    <link media="screen" type="text/css" href="/adminfiles/css/jquery-ui.min.css" rel="StyleSheet">
     <link media="screen" type="text/css" href="/adminfiles/css/jquery.fancybox.css" rel="StyleSheet">

     <script type="text/javascript" src="/adminfiles/js/jquery-1.12.0.min.js"></script>
     <script type="text/javascript" src="/adminfiles/js/jquery-ui.min.js"></script>
     <script type="text/javascript" src="/adminfiles/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/adminfiles/js/bootstrap-select.min.js"></script>
     <script type="text/javascript" src="/adminfiles/js/jquery.fancybox.js"></script>
     <script type="text/javascript" src="/adminfiles/js/cimesCms.js"></script>
 <script type="text/javascript" src="/adminfiles/js/download.js"></script>
    <script type="text/javascript" src="/adminfiles/tinymce/tinymce.min.js"></script>

 </head>
 <body>
 <div class="main-container">