<div class="message-login"><?php if(isset($message)){ echo $message; unset($message);} ?></div>
<div class="page-header"><?= ATXT_SNIPPETS_ADD; ?></div>

<?php if(isset($_POST['snip_type'])): ?>

    <?php $sniptype = $_POST['snip_type']; ?>

<form class="admin-form form-big" id="add_snippet_form" name="add_snippet_form" role="form" method="post" action="/admin/snippets/save" enctype="multipart/form-data">

    <input type="hidden" id="add_snip_type" name="add_snip_type" value="<?= $sniptype; ?>"/>
    <div class="row no-margin">
        <div class="col-lg-12">
            <div class="form-group margin-bottom">
                <label for="add_snip_name" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= SNIP_NAME_ADVICE; ?>">  * <?= SNIP_NAME; ?>  </label>
                <input type="text" class="form-control " id="add_snip_name" name="add_snip_name"  placeholder="nazwa nie może zawierać spacji lub polskich znaków"/>
            </div>
        </div>
    </div>

    <div class="row no-margin">
        <div class="col-lg-12">
            <div class="form-group">
                <label for="add_snip_code" class="tooltip-labels" data-toggle="tooltip" data-placement="top" title="<?= SNIP_CODE_ADVICE; ?>"> * <?= POST_POST_DESCRIPTION; ?>  </label>
                <textarea class="form-control textarea-table" placeholder="" rows="16" id="add_snip_code" name="add_snip_code"></textarea>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12"><button type="submit" class="btn btn-default full-width" id="add_snippet" name="add_snippet"><?= SNIP_SAVE; ?></div>
    </div>

</form>

<?php endif; ?>
